### ISSUE TITLE
Requirement for making a release to crates.io

### ISSUE THREAD

**Issue by BusyJay** [pingcap/raft-rs#1]
Before publishing this crate, we need to resolve following issues.

- [x] Drop unnecessary dependencies
- [x] Move protos out of kvproto
- [x] Make it compile with stable compiler
- [x] Add Readme
- [ ] Add examples
- [ ] Add documentations
- [x] Add CI check

Closes #16.

**Comment by Hoverbear** [comment]
I don't think there are any unnecessary dependencies anymore.

**Comment by siddontang** [comment]
@BusyJay 

Seem it is hard for us to move protos out of kvproto now, we can cross off this item.

**Comment by BusyJay** [comment]
We can archive this via wget and sed in kvproto. I strongly recommend to drop the kvproto dependency. So raft-rs won't depend on many unnecessary messages and drop the grpcio dependency.

**Comment by fabianfreyer** [comment]
@BusyJay would it be possible to completely drop serialization and instead define a `Trait` that provides serialization and communication routines, so that things depending on `raft-rs` can implement these? You could then still ship a `protobuf` implementation using the protos in `kvproto`.

**Comment by BusyJay** [comment]
@fabianfreyer thanks for the advice. Serialization and Deserialization usually will affect how the struct is defined. For example, if we want to enable zero-copy, then there may be a lifetime in the definition of `Entry` struct, and `Vec` should be changed to `&[u8]` or `Bytes`. It's nearly impossible to adapt to all serialization framework with the same struct. Maybe one working method is to use Generic instead of concrete types, but this requires a big changes. It may be done in the future releases but not in the first release, which we hope to finish in the following several weeks.

**Comment by fabianfreyer** [comment]
@BusyJay Thanks for considering this! The points you make make sense. Using generic types does seem to be a good idea. However, I do agree with your prioritization of getting the library released.

**Comment by BusyJay** [comment]
We are going to release version 0.1 as major issues are resolved. We will release 1.0 as the remaining issues are resolved.
