### ISSUE TITLE
consider degrading log version from 0.4 to 0.3

### ISSUE THREAD

**Issue by siddontang** [pingcap/raft-rs#113]
It shows Unknown for the file name in TiKV log, and hard to debug for us.

**Comment by BusyJay** [comment]
I don't think it's a bug of this crate. Better let TiKV upgrade its log dependency to 0.4.

**Comment by siddontang** [comment]
now, it is hard to upgrade to log 0.4 because slog doesn't support it.

@breeswish

**Comment by BusyJay** [comment]
Then it sounds like a bug of slog.

**Comment by siddontang** [comment]
yes, but now we have no time to fix it for slog. So the better way is to degrade log version.

**Comment by breeswish** [comment]
I don't think it's a good idea. Downgrading a dependency to an outdated version is not friendly for the community. Other people who are using this crate will suffer issues. Meanwhile, we are not meeting much trouble when raft.rs using log 0.4.
