### ISSUE TITLE
Lease based read-only request without `check_quorum` behaves wrong.

### ISSUE THREAD

**Issue by rustonaut** [pingcap/raft-rs#140]
Lease based read-only request without `check_quorum` behaves wrong, at least in outdated leader in a minority partition.

In `step_leader` for handling `MsgReadIndex` messages.

https://github.com/pingcap/raft-rs/blob/3799cfa482e288a0fc4a3a6c365c6681afd85b3a/src/raft.rs#L1429-L1449

I think line `1437` should use `read_index` instead of `self.raft_log.commited`, if
I'm not wrong (and if I'm wrong the `read_index` variable should be created in
the `else` branch to prevent confusion).

If my understanding of the code is correct then lease base read requests allow
you to read up to the commit index _iff_ `self.check_quorum` is set as this would
make sure that the leader still has the majority behind them and return `INVALID_INDEX`
if not (which btw. seems to be kind of a strange, shouldn't then `Config::validate` at last
warn on using a leas based reads without `check_quorum`).

**Comment by Hoverbear** [comment]
Hi @rustonaut , can you take a look at #141 . I think you are correct.

**Comment by rustonaut** [comment]
I think it's correct, long term we might want to consider to maybe warn if
lease baseed reads are used without `check_quorum` as this would be a
non-time limited lease in case of a long-term/permanent network partition.
