### ISSUE TITLE
raft : Incorrect learner checking in handle_transfer_leader

### ISSUE THREAD

**Issue by Fullstop000** [pingcap/raft-rs#164]
https://github.com/pingcap/raft-rs/blob/2bd26cea006a67a36778adbcc3525f83765c044d/src/raft.rs#L1206-L1211
Here we should check whether target `Progress` is a learner instead and besides `self.is_learner` is never true since self is the leader.

**Comment by hicqu** [comment]
Nice catch, thank you. I will fix it soon later.
