### ISSUE TITLE
raft: ReadIndex request dropping happens

### ISSUE THREAD

**Issue by Fullstop000** [pingcap/raft-rs#167]
From @zhongleihe https://github.com/tikv/tikv/issues/4071

https://github.com/pingcap/raft-rs/blob/2bd26cea006a67a36778adbcc3525f83765c044d/src/raft.rs#L1185-L1203

The line 1201 assigning `Some(to_send)` to `more_to_send` overrides the previous `more_to_send `assignment which drops `ReadIndex` request actually.

Generally, assuming leader can receive a majority of heartbeat responses from followers and there is no network isolation or variation, the issue above can hardly happens because there is always only one `ReadIndex` request that leader can handle per heartbeat round.

**Comment by siddontang** [comment]
Thanks @Fullstop000 

Can you send us a PR to fix it?

**Comment by Fullstop000** [comment]
@siddontang working on it.
