### ISSUE TITLE
Config.peers and Config.learners should be private

### ISSUE THREAD

**Issue by Fullstop000** [pingcap/raft-rs#172]
For now `peers` and `learners` are public for testing convenience ( probably because almost all the tests are seperated into an another mod )
https://github.com/pingcap/raft-rs/blob/24280e8f0f9e9a38d8aa62cfb42d1f2f3cf0a026/src/config.rs#L39-L51

And that the comments are somewhat ambiguous could lead a misuse ( for details see https://github.com/pingcap/raft-rs/issues/170)

Maybe we can revise the comments to be more clear and make the both fields private later

**Comment by hicqu** [comment]
How about remove these 2 fields? For testing we can add a new functions to initialize the raft node.

**Comment by Fullstop000** [comment]
@hicqu using a func like e.g. `Raft::new_test_raft`  is ok for me.

**Comment by Hoverbear** [comment]
As a result of https://github.com/pingcap/raft-rs/pull/196/files#diff-6d8a5e2104954a026de2bfe2b936aea4L39 we no longer have these fields in the config!
