### ISSUE TITLE
raft: fix deadlock during PreVote migration process

### ISSUE THREAD

**Issue by siddontang** [pingcap/raft-rs#20]
refer https://github.com/coreos/etcd/pull/8525

**Comment by csmoe** [comment]
The `pre_vote` field of `Raft` is private:
```
pub struct Raft<T: Storage> {
    ...
    pub check_quorum: bool,
    pre_vote: bool,
    ...
```
but `pre_vote` was changed directly in https://github.com/coreos/etcd/pull/8525 : 
```
func newPreVoteMigrationCluster(t *testing.T) *network {
    ...
    n1.preVote = true
    ... 
```
I couldn't find any methods to change the value of `pre_vote` after a `raft` was  instantiated, how can I reset the `pre_vote` field of a `raft`?

**Comment by siddontang** [comment]
Hi @csmoe 

Seem you can make the field public like `check_quorum` does
