### ISSUE TITLE
Is there a friendly way to re-generate eraftpb.rs 

### ISSUE THREAD

**Issue by Fullstop000** [pingcap/raft-rs#236]
It seems that I have to modify the `build.rs` or `Cargo.toml` and then run `cargo build` If I want to re-generate the eraftpb.rs via Prost. Is there a more convenient way to do this? ( BTW the part of this in [README.md](https://github.com/pingcap/raft-rs/blob/master/README.md#modifying-protobufs) is out of date)

**Comment by siddontang** [comment]
PTAL @nrc

**Comment by nrc** [comment]
`cargo build --features gen` should regenerate it. Let me know if it works, of not I will fix, if so I can fix README.md :-)

**Comment by Fullstop000** [comment]
@nrc thank you and it works with `cargo build --features gen`. Can I use it with `cargo watch` to generate `eraftpb.rs` automatically?

**Comment by nrc** [comment]
>  Is there a convenient approach for automatically generating in development?

Not that I know of, I don't use `cargo watch` myself. Perhaps `cargo watch --features gen` would work? I expect something similar to that should work

**Comment by Fullstop000** [comment]
@nrc `cargo watch -s "cargo check --features gen"` works! I miss the `-s` option. You can just close this issue after fix `README.md`
