### ISSUE TITLE
How to resolve ProposalDropped Error

### ISSUE THREAD

**Issue by ckanner** [pingcap/raft-rs#280]
When I use `raw_node` to propose a message, it may be occur `ProposalDropped Error`.

My question is:
* Under what circumstances an `ProposalDropped Error` will occur?
* How can I resolve this error? I do not want to propagate the error to the fronted client.
* I read the code of tikv, and find it may not resolve this error when it occur, and just propagate. And I can not see some retry work.

**Comment by Fullstop000** [comment]
> Under what circumstances an ProposalDropped Error will occur?

Send a proposal to a node in states below: 
- Candidate 
- Learner
- Follower who doesn't know the leader
- Leader who has a in-progress leader transferring

> How can I resolve this error? I do not want to propagate the error to the fronted client.

I think it depends on your scenario. IMO, re-sending the proposal will be the most common solution.

> And I can not see some retry work.

@BusyJay

**Comment by ckanner** [comment]
It has some code in raft.rs
```
MessageType::MsgPropose => {
                if m.get_entries().is_empty() {
                    panic!("{} stepped empty MsgProp", self.tag);
                }
                if !self.prs().voters().contains_key(&self.id) {
                    // If we are not currently a member of the range (i.e. this node
                    // was removed from the configuration while serving as leader),
                    // drop any new proposals.
                    return Err(Error::ProposalDropped);
                }
```
It matches which state?
* Candidate
* Learner
* Follower who doesn't know the leader
* Leader who has a in-progress leader transferring

@Fullstop000

**Comment by Fullstop000** [comment]
As it is documented, this could be a special situation where the ConfChange removes the leader itself. Also, the more common scenario is that a learner is never included in voters.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BusyJay** [comment]
I think it's a bug in TiKV master. It should report special error instead of `ProposalDropped`. /cc @hicqu

**Comment by hicqu** [comment]
Here the error is expected, but the condition should be `voters_and_learners.contains(&self.id)`. I will fix it later.

**Comment by hicqu** [comment]
I have double checked the place. It's for the case that the peer is removed as a leader, so the condition is ok here. It doesn't need any fix.
PTAL @ckanner .

**Comment by ckanner** [comment]
`Leader who has a in-progress leader transferring`

**Comment by ckanner** [comment]
`Leader who has a in-progress leader transferring` 
It may not occur in this condition?
@hicqu

**Comment by hicqu** [comment]
@ckanner sorry for responsing late. I'm not sure what you mean in your last question. Could you give me more detail?

**Comment by ckanner** [comment]
@hicqu 
The above you mean `ProposalDropped` just occurs when the peer is removed as a leader in tikv, yeah?

I want know, when Leader who has a in-progress leader transferring, `ProposalDropped` may not occurs in tikv?

**Comment by hicqu** [comment]
> ProposalDropped just occurs when the peer is removed as a leader in tikv.
It's just 1 possible case. Other cases are listed by @Fullstop000 
* Candidate
* Learner
* Follower who doesn't know the leader
* Leader who has a in-progress leader transferring

**Comment by hicqu** [comment]
@ckanner could I close it now?

**Comment by ckanner** [comment]
ok @hicqu
