### ISSUE TITLE
Allow users to not pass a `slog` logger for `RawNode`

### ISSUE THREAD

**Issue by LucioFranco** [pingcap/raft-rs#301]
Currently, on the master branch, it is required that uses pass a slog logger to create a `RawNode`. This is a hindrance to people who want to get started but have not learned the slog crate.

**Comment by Hoverbear** [comment]
Seems this is from #288 in https://github.com/pingcap/raft-rs/pull/288/files#diff-3e643971842b1203495f3e09ab4b6832
