### ISSUE TITLE
Determine a Rust version tracking strategy.

### ISSUE THREAD

**Issue by Hoverbear** [pingcap/raft-rs#6]
Currently `tikv`, the main consumer of this crate, tracks a specific nightly release, with infrequent jumps. This is a very acceptable strategy for a binary, however it's not ideal for a small library like `raft`. If we were to require a specific version of Rust we may cause downstream issues.

I see a couple possible strategies:

* Track `nightly` but don't adopt changes which break compatibility with `tikv`, this can be done by doing a pair of builds, one on `tikv`'s version and one on `master` during CI.
* Stabilize on `stable` so everyone can use the crate.

**Comment by BusyJay** [comment]
We always keep our library work on stable channel, like grpc-rs, prometheus-rs. To use features only available in nightly rust, we can add additional features to enable them conditionally.

**Comment by Hoverbear** [comment]
`raft-rs` will continue to be a stable compatible library for the forseeable future. :tada:
