### ISSUE TITLE
Should `become_pre_candidate` call `reset`?

### ISSUE THREAD

**Issue by Hoverbear** [pingcap/raft-rs#76]
Currently `become_pre_candidate` does not call `self.reset(term)` like the other `become_*` functions:

https://github.com/pingcap/raft-rs/blob/a6671bed1d37805667afa022a84825477fc17e9b/src/raft.rs#L821-L832

https://github.com/pingcap/raft-rs/blob/a6671bed1d37805667afa022a84825477fc17e9b/src/raft.rs#L835-L842

https://github.com/pingcap/raft-rs/blob/a6671bed1d37805667afa022a84825477fc17e9b/src/raft.rs#L807-L814

https://github.com/pingcap/raft-rs/blob/a6671bed1d37805667afa022a84825477fc17e9b/src/raft.rs#L799-L800

This created an interesting situation in https://github.com/pingcap/tikv/pull/3133, since `self.reset(term)` is not called the `leader_id != INVALID_ID` which was what we were using to detect if the leader was missing in `check_stale_state` [here](https://github.com/pingcap/tikv/blob/master/src/raftstore/store/peer.rs#L725-L728).

The thesis on prevote:

> If desired, Raft’s basic leader election algorithm can be extended with an
> additional phase to prevent such disruptions, forming the Pre-Vote algorithm.
> In the Pre-Vote algorithm, a candidate only increments its term if it first
> learns from a majority of the cluster that they would be willing to grant the
> candidate their votes (if the candidate’s log is sufficiently up-to-date, and
> the voters have not received heartbeats from a valid leader for at least a
> baseline election timeout). This was inspired by ZooKeeper’s algorithm [42],
> in which a server must receive a majority of votes before it calculates a new
> epoch and sends NewEpoch messages (however, in ZooKeeper servers do not
> solicit votes, other servers offer them).
>
> The Pre-Vote algorithm solves the issue of a partitioned server disrupting
> the cluster when it rejoins. While a server is partitioned, it won’t be able
> to increment its term, since it can’t receive permission from a majority of
> the cluster. Then, when it rejoins the cluster, it still won’t be able to
> increment its term, since the other servers will have been receiving regular
> heartbeats from the leader. Once the server receives a heartbeat from the
> leader itself, it will return to the follower state (in the same term).
>
> We recommend the Pre-Vote extension in deployments that would benefit from
> additional robustness. We also tested it in various leader election scenarios
> in AvailSim, and it does not appear to significantly harm election
> performance.

**Comment by BusyJay** [comment]
I think it's intended. The pre-vote is just an experiment, so the node should keep its state until election is really happening.
