### ISSUE TITLE
Ready is Ready-Only, should only have getters.

### ISSUE THREAD

**Issue by Hoverbear** [pingcap/raft-rs#90]
The `Ready` struct should not allow values to be mutated, it should only provide immutable getters.

https://github.com/pingcap/raft-rs/blob/1e0741a9aea3b242d33dadc46245ad611e7e7aa4/src/raw_node.rs#L84-L121

It's possible to do this by writing functions that return immutable borrows of the contained values, or using a crate like https://crates.io/crates/getset which will write them for you.

**Comment by Ryan-Git** [comment]
After adding getter, shall we remove pub modifier? It would be a breaking change then.

**Comment by Ryan-Git** [comment]
@siddontang 
ok. I'll working on this.
