### ISSUE TITLE
Convert `Storage::entries`'s `max_size` argument to `Option<u64>`

### ISSUE THREAD

**Issue by bkchr** [pingcap/raft-rs#98]
Currently the value is just a `u64` with `u64::MAX` defined as `NO_LIMIT`.
This no limit is not mentioned in the documentation. Something like the following enum would suite better:
```
enum Size {
    Fixed(u64),
    NoLimit,
}; 
```

I could provide a PR, if wanted.

Edit (brson): per discussion, let's change this to `Option<u64>` with a doc-comment explaining that `None` means "no limit". The `Storage` trait is in `src/storage.rs`.

**Comment by siddontang** [comment]
Maybe adding a comment is better.

/cc @Hoverbear

**Comment by Hoverbear** [comment]
@bkchr Would adding a comment about this limit be satisfactory? Since `NoLimit == Fixed(u64::MAX)`

**Comment by Hoverbear** [comment]
Perhaps `Option<u64>` is appropriate. A `None` value correctly communicates that `The max size is none.`

**Comment by Hoverbear** [comment]
@bkchr Would you still be interested in making a PR, or is this open for others to tackle?

**Comment by bkchr** [comment]
Open for others :)

**Comment by estk** [comment]
Id like to work on this!

**Comment by estk** [comment]
dang, too slow :/

**Comment by estk** [comment]
Sure thing @pwoolcoc, you're too quick on the draw :)

**Comment by Hoverbear** [comment]
@estk Aw, thanks so much! Do you think you might be interested in this one instead? https://github.com/pingcap/raft-rs/issues/70

**Comment by estk** [comment]
@Hoverbear haha, you really gotta be quick here! Thanks for pointing that one out, but it looks like I'm too late again. I'll be away for the weekend but I'll swing back next week and try to pick up an issue. Thanks for the hospitality @Hoverbear

**Comment by Hoverbear** [comment]
🤦‍♀️ Ha, I'm sorry. :)
